-- Tienda -- 

SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SHOW COLUMNS FROM producto;
SELECT nombre, precio, cast(precio * 0.82 as DECIMAL(6,2)) FROM producto;
SELECT nombre, precio as Euros, cast(precio * 0.82 as DECIMAL(6,2)) 'Dolars' FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, UPPER(SUBSTRING(nombre,1,2)) from fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, TRUNCATE(precio,0) FROM producto;
SELECT  p.codigo_fabricante  from fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT DISTINCT p.codigo_fabricante  from fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3,2;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre as Producto, p.precio, f.nombre as Fabricante FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante;
SELECT p.nombre as Producto, p.precio, f.nombre as Fabricante FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY f.nombre;
SELECT p.codigo, p.nombre as 'Nombre Producto',f.codigo, f.nombre as 'Fabricante' FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante;
SELECT p.nombre as 'Producto', p.precio, f.nombre AS 'Fabricante' FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY p.precio LIMIT 1; 
SELECT p.nombre as 'Producto', p.precio, f.nombre AS 'Fabricante' FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY p.precio DESC LIMIT 1; 
SELECT * FROM producto JOIN fabricante f ON f.codigo = producto.codigo_fabricante WHERE f.nombre = 'Lenovo';
SELECT * FROM producto JOIN fabricante f ON f.codigo = producto.codigo_fabricante WHERE f.nombre = 'Crucial' AND producto.precio > 200;
SELECT * FROM producto JOIN fabricante f ON f.codigo = producto.codigo_fabricante WHERE f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate';
SELECT * FROM producto JOIN fabricante f ON f.codigo = producto.codigo_fabricante WHERE f.nombre IN('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre LIKE '%e'; 
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre LIKE '%w%'; 
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC; 
SELECT DISTINCT f.nombre, p.nombre FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT DISTINCT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT DISTINCT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante WHERE p.nombre IS NULL;
SELECT p.nombre FROM producto p WHERE codigo_fabricante IN (SELECT codigo FROM fabricante WHERE nombre = 'lenovo');
SELECT * FROM producto WHERE precio = (SELECT precio FROM producto WHERE codigo_fabricante IN ( SELECT codigo FROM fabricante WHERE nombre = 'lenovo') ORDER BY precio DESC LIMIT 1); 
SELECT nombre FROM producto WHERE codigo_fabricante IN ( SELECT codigo FROM fabricante WHERE nombre = 'lenovo') ORDER BY precio DESC LIMIT 1; 
SELECT nombre FROM producto WHERE codigo_fabricante IN ( SELECT codigo FROM fabricante WHERE nombre = 'hewlett-packard') ORDER BY precio LIMIT 1; 
SELECT * FROM producto WHERE precio >= (SELECT precio FROM producto WHERE codigo_fabricante IN ( SELECT codigo FROM fabricante WHERE nombre = 'lenovo') ORDER BY precio DESC LIMIT 1); 
SELECT * FROM producto JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante WHERE fabricante.nombre = 'Asus' AND precio >= (SELECT AVG(precio) FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Asus');

--Universidad--

SELECT apellido1, apellido2, nombre FROM persona WHERE id IN (SELECT id_alumno FROM alumno_se_matricula_asignatura);
SELECT apellido1, apellido2, nombre FROM persona WHERE telefono IS NULL and id IN (SELECT id_alumno FROM alumno_se_matricula_asignatura);
SELECT apellido1, apellido2, nombre FROM persona WHERE YEAR(fecha_nacimiento) = 1999 AND id IN(SELECT id_alumno FROM alumno_se_matricula_asignatura);
SELECT * FROM persona WHERE telefono IS NULL AND id IN (SELECT id_profesor FROM profesor) AND nif LIKE '%k';
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT p.apellido1, p.apellido2, p.nombre, d.nombre as departamento FROM persona p JOIN profesor pr ON p.id = pr.id_profesor JOIN departamento d ON pr.id_departamento = d.id ORDER BY p.apellido1 ASC, p.apellido2 ASC, p.nombre ASC;
SELECT a.nombre, c.anyo_inicio, c.anyo_fin FROM asignatura a JOIN alumno_se_matricula_asignatura al ON al.id_asignatura = a.id JOIN curso_escolar c ON c.id = al.id_curso_escolar JOIN persona p ON p.id = al.id_alumno WHERE p.nif = '26902806M';
SELECT d.nombre FROM departamento d JOIN profesor p ON d.id = p.id_departamento JOIN asignatura a ON a.id_profesor = p.id_profesor JOIN grado g ON g.id = a.id_grado WHERE g.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT * FROM persona p JOIN alumno_se_matricula_asignatura al ON p.id = al.id_alumno JOIN curso_escolar c ON c.id = al.id_curso_escolar WHERE c.anyo_inicio = '2018';
SELECT p.nombre, p.apellido1, p.apellido2, d.nombre as 'Departamento' FROM persona p JOIN profesor pr ON p.id = pr.id_profesor RIGHT JOIN departamento d ON d.id = pr.id_departamento ORDER BY d.nombre, p.apellido1, p.apellido2, p.nombre;
SELECT id_profesor, nombre as 'departamento' FROM profesor LEFT JOIN departamento ON id_departamento = id WHERE nombre IS NULL;
SELECT id_profesor, nombre as 'departamento' FROM profesor RIGHT JOIN departamento ON id_departamento = id WHERE id_profesor IS NULL;
SELECT p.id_profesor, pr.nombre as 'profesor', a.id, a.nombre as asignaturas FROM profesor p LEFT JOIN asignatura a ON p.id_profesor = a.id_profesor JOIN persona pr ON pr.id = p.id_profesor WHERE a.id IS NULL;
SELECT p.id_profesor, a.nombre as asignaturas FROM profesor p RIGHT JOIN asignatura a ON p.id_profesor = a.id_profesor WHERE p.id_profesor IS NULL;
SELECT DISTINCT d.id, d.nombre as 'Departamento', a.nombre FROM  departamento d LEFT JOIN profesor p ON p.id_departamento = d.id LEFT JOIN asignatura a ON a.id_profesor = p.id_profesor WHERE a.id IS NULL;            
SELECT count(*) as TotalAlumnos FROM persona WHERE tipo = 'alumno';
SELECT count(*) as TotalAlumnos FROM persona WHERE YEAR(fecha_nacimiento) = 1999 AND tipo = 'alumno';
SELECT nombre as 'Departamento', count(id_profesor) as nProfesor FROM departamento JOIN profesor ON profesor.id_departamento = departamento.id GROUP BY departamento.nombre ORDER BY nProfesor;
SELECT d.nombre AS 'Departamento', pe.apellido1, pe.apellido2, pe.nombre FROM departamento d LEFT JOIN profesor p ON d.id = p.id_departamento LEFT JOIN persona pe ON pe.id = p.id_profesor;  
SELECT g.nombre AS 'Grado', Count(a.id_grado) as NumAsignaturas FROM grado g LEFT JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre ORDER BY NumAsignaturas DESC;
SELECT g.nombre AS 'Grado', Count(a.id_grado) as NumAsignaturas FROM grado g LEFT JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre having COUNT(A.ID_GRADO) > 40 ORDER BY NumAsignaturas DESC;
SELECT g.nombre AS 'Grado', A.TIPO as 'Tipo Asignatura', SUM(a.creditos) AS 'Total Creditos' FROM grado g JOIN asignatura a ON g.id = a.id_grado GROUP BY a.tipo, g.nombre ORDER BY g.nombre, a.tipo;
SELECT c.anyo_inicio, count(id_curso_escolar) FROM curso_escolar c JOIN alumno_se_matricula_asignatura al ON c.id = al.id_curso_escolar GROUP BY c.anyo_inicio;
SELECT p.id, p.nombre as 'Nombre', p.apellido1, p.apellido2, COUNT(a.id_profesor) as Numero_Asignaturas FROM persona p JOIN profesor pr ON p.id = pr.id_profesor LEFT JOIN asignatura a ON a.id_profesor = pr.id_profesor GROUP BY pr.id_profesor ORDER BY Numero_Asignaturas DESC;
SELECT * FROM persona WHERE tipo = 'alumno' ORDER BY YEAR(fecha_nacimiento) DESC LIMIT 1; 
SELECT p.nombre, pr.id_profesor FROM profesor pr LEFT JOIN asignatura a ON pr.id_profesor = a.id_profesor JOIN persona p ON p.id = pr.id_profesor WHERE a.id IS NULL;