SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SHOW COLUMNS FROM producto;
SELECT nombre, precio, cast(precio * 0.82 as DECIMAL(6,2)) FROM producto;
SELECT nombre, precio as Euros, cast(precio * 0.82 as DECIMAL(6,2)) 'Dolars' FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, UPPER(SUBSTRING(nombre,1,2)) from fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, TRUNCATE(precio,0) FROM producto;
SELECT  p.codigo_fabricante  from fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT DISTINCT p.codigo_fabricante  from fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3,2;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre as Producto, p.precio, f.nombre as Fabricante FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante;
SELECT p.nombre as Producto, p.precio, f.nombre as Fabricante FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY f.nombre;
SELECT p.codigo, p.nombre as 'Nombre Producto',f.codigo, f.nombre as 'Fabricante' FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante;
SELECT p.nombre as 'Producto', p.precio, f.nombre AS 'Fabricante' FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY p.precio LIMIT 1; 
SELECT p.nombre as 'Producto', p.precio, f.nombre AS 'Fabricante' FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY p.precio DESC LIMIT 1; 
SELECT * FROM producto JOIN fabricante f ON f.codigo = producto.codigo_fabricante WHERE f.nombre = 'Lenovo';
SELECT * FROM producto JOIN fabricante f ON f.codigo = producto.codigo_fabricante WHERE f.nombre = 'Crucial' AND producto.precio > 200;
SELECT * FROM producto JOIN fabricante f ON f.codigo = producto.codigo_fabricante WHERE f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate';
SELECT * FROM producto JOIN fabricante f ON f.codigo = producto.codigo_fabricante WHERE f.nombre IN('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre LIKE '%e'; 
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre LIKE '%w%'; 
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC; 
SELECT DISTINCT f.nombre, p.nombre FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT DISTINCT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT DISTINCT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante WHERE p.nombre IS NULL;
SELECT p.nombre FROM producto p WHERE codigo_fabricante IN (SELECT codigo FROM fabricante WHERE nombre = 'lenovo');
SELECT * FROM producto WHERE precio = (SELECT precio FROM producto WHERE codigo_fabricante IN ( SELECT codigo FROM fabricante WHERE nombre = 'lenovo') ORDER BY precio DESC LIMIT 1); 
SELECT nombre FROM producto WHERE codigo_fabricante IN ( SELECT codigo FROM fabricante WHERE nombre = 'lenovo') ORDER BY precio DESC LIMIT 1; 
SELECT nombre FROM producto WHERE codigo_fabricante IN ( SELECT codigo FROM fabricante WHERE nombre = 'hewlett-packard') ORDER BY precio LIMIT 1; 
SELECT * FROM producto WHERE precio >= (SELECT precio FROM producto WHERE codigo_fabricante IN ( SELECT codigo FROM fabricante WHERE nombre = 'lenovo') ORDER BY precio DESC LIMIT 1); 
SELECT * FROM producto JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante WHERE fabricante.nombre = 'Asus' AND precio >= (SELECT AVG(precio) FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Asus');